softwaremill/adopt-tapir

- backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterModel.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterService.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterApi.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequest.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequestValidator.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectTemplate.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/sbt/BuildSbtView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/APIDefinitionsView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/Code.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/EndpointsSpecView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/EndpointsView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/MainView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/PlainLogicWithImports.scala
- backend/src/main/twirl/ApiDefinitions.scala.txt
- backend/src/main/twirl/ApiDefinitionsSpec.scala.txt
- backend/src/main/twirl/Endpoints.scala.txt
- backend/src/main/twirl/EndpointsSpec.scala.txt
- backend/src/main/twirl/MainFutureAkka.scala.txt
- backend/src/main/twirl/MainFutureNetty.scala.txt
- backend/src/main/twirl/MainIOHttp4s.scala.txt
- backend/src/main/twirl/MainIONetty.scala.txt
- backend/src/main/twirl/MainZIOHttp4s.scala.txt
- backend/src/main/twirl/MainZIOhttpZIO.scala.txt
- backend/src/test/scala/com/softwaremill/adopttapir/starter/FileOperation.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITSpec.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/FormValidatorSpec.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterRequestGenerators.scala
- development/http-client.http
> Support for optional documentation endpoints.

- backend/src/main/resources/template/plugins.sbt
- backend/src/main/resources/template/scalafmt.conf
- backend/src/main/scala/com/softwaremill/adopttapir/starter/FormatScalaFiles.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterService.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectTemplate.scala
- build.sbt
> Add scalafmt to generated template and format generated files

- backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterModel.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequestValidator.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/sbt/BuildSbtView.scala
- backend/src/main/twirl/MainIONetty.scala.txt
- backend/src/main/twirl/MainZIOHttp4s.scala.txt
- backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/FormValidatorTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterRequestGenerators.scala
- backend/src/test/scala/com/softwaremill/adopttapir/test/Requests.scala
- backend/src/test/scala/com/softwaremill/adopttapir/test/Rich.scala
- backend/src/test/scala/com/softwaremill/adopttapir/test/TestDependencies.scala
- development/http-client.env.json
- development/http-client.http
> Add server stub test

- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequestValidator.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/FormValidatorTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala
- ui/src/components/ConfigurationForm/ConfigurationForm.consts.ts
closes https://github.com/softwaremill/adopt-tapir/issues/30
> Allow _ in project name

- backend/src/main/resources/template/README.md
- backend/src/main/resources/template/sbtx
- backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterService.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectTemplate.scala
- backend/src/main/scala/com/softwaremill/adopttapir/util/ZipArchiver.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/util/ZipArchiverTest.scala
- build.sbt
Used apache commons lib which allows to set unix permissions at zip file. 
Added Readme.md.
> 9 add to zipped file script wrapper similar to gradlew which allows to build a project without natively installed sbt

- backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterService.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectTemplate.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/template/ProjectTemplateTest.scala
closes https://github.com/softwaremill/adopt-tapir/issues/48
> Legalizing package names if they starts with a digit

- backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectTemplate.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/sbt/BuildSbtView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/sbt/Dependency.scala
- backend/src/main/twirl/EndpointsSpecZIO.scala.txt
- backend/src/main/twirl/sbtBuild.scala.txt
> Use zio-test when generating a zio project

- .github/workflows/scala-steward.yml
- .mergify.yml
- .scala-steward.conf
- backend/src/main/resources/application.conf
- backend/src/main/resources/template/scalafmt.conf
- backend/src/main/scala/com/softwaremill/adopttapir/http/HttpApi.scala
- backend/src/main/scala/com/softwaremill/adopttapir/metrics/Metrics.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterConfig.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterModel.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequest.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequestValidator.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectTemplate.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/sbt/BuildSbtView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/sbt/Dependency.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/MainView.scala
- backend/src/main/twirl/scalafmt.scala.txt
- backend/src/test/scala/com/softwaremill/adopttapir/starter/FileOperation.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/FormValidatorTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterRequestGenerators.scala
- backend/src/test/scala/com/softwaremill/adopttapir/template/ProjectTemplateTest.scala
- build.sbt
- development/http-client.http
- ui/src/api/starter.ts
- ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx
- ui/src/components/ConfigurationForm/ConfigurationForm.consts.ts
- added scala-steward action
- All dependencies used for template generation moved to build.sbt
- sbt version moved to build.sbt
- scala formatter version moved to build.sbt
- tapir version moved to build.sbt and removed from UI. It will take latest version from build.sbt
> 25 automatically update sttp jsoniter dependencies

- backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala
At present each scenario is logged with a single line e.g.
```
[info] - should return zip file containing working sbt folder with: FutureEffect/Akka/docs=true/metrics=true/WithoutJson
```
that implicitly means that apart from 'hello' endpoint 'docs' and
'metrics' endpoints will be tested too (corresponding values are 'true')
however it is not reflected in the test log. It is might be especially
helpful in the event of failure.
With this change log contains addition part that indicates which sub
test was finished e.g.:
```
[info] - should return zip file containing working sbt folder with: FutureEffect/Akka/docs=true/metrics=true/WithoutJson
[info]   + should have helo endpoint available
[info]   + should have docs endpoint available
[info]   + should have metrics endpoint available
```
> chore: add information about finished sub test

- backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala
Hide implementation details in a dedicated  case class so that
'ServiceUnderTest' is cleaner and not responsible for log.
Closes #13
> chore: encapsulate StringBuilder in RunLogger

- .github/workflows/adopt-tapir-ci.yml
> Add a `build docker image locally` step during CI

- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/EndpointsView.scala
- backend/src/main/twirl/Endpoints.scala.txt
> Remove unnecessary imports from Endpoints.scala template

- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/EndpointsView.scala
- backend/src/main/twirl/EndpointsSpec.scala.txt
- backend/src/main/twirl/EndpointsSpecZIO.scala.txt
* Removed redundant `AtomicReference` wrapping list of books.
* Changed the way `books` are referenced.
* Updated integration tests
> Improvements to library

- backend/src/main/scala/com/softwaremill/adopttapir/http/Http.scala
- backend/src/main/scala/com/softwaremill/adopttapir/infrastructure/Json.scala
- backend/src/main/scala/com/softwaremill/adopttapir/util/package.scala
- build.sbt
* Removed unused usages of `TSec`'s `SecureRandomId` in the project.
* Removed unused `TSec` dependency itself.
> Remove unused tsec library

- README.md
- ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx
* On frontend side - allowed changing server address by specifying environmental variable, so that it is possible to easily plug it to localhost backend.
* Updated `README.md` accordingly.
> Make backend fronted work locally with each other

- build.sbt
> chore: upgrade scala 3 to version 3.2.0

- ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx
- ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.component.test.tsx
So that it better reflects the intention behind the section.
Created as from comment to #130
> feat: rename 'Builder' section to 'Build tool'

- ui/src/components/CommonSnackbar/CommonSnackbar.component.tsx
- ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx
- ui/src/components/ConfigurationForm/ConfigurationForm.styles.ts
- ui/src/components/FormTextField/FormTextField.component.tsx
- ui/src/hooks/useInitialData.ts
- ui/src/hooks/useSharedConfig.ts
Changes:
* remove duplicated `SnackbarConfig` interface
* call `yarn lint` on changes
> chore: post-ui changes fixes

- ui/README.md
> fix: add 'allow-popups' permission to the iframe definition

- ui/README.md
> fix: iframe height

- ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx
- ui/src/components/ConfigurationForm/ConfigurationForm.styles.ts
fixed error in devtools: 
as well as aligned the "Server implementation" info icon.
**before:**
**after:**
> fix: MUI error + icon alignment

- backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterModel.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequest.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequestValidator.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/BuildView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/MainView.scala
- backend/src/main/twirl/MainFutureVertx.scala.txt
- backend/src/main/twirl/MainFutureVertxScala3.scala.txt
- backend/src/main/twirl/MainIOVertx.scala.txt
- backend/src/main/twirl/MainIOVertxScala3.scala.txt
- backend/src/main/twirl/MainZIOVertx.scala.txt
- backend/src/main/twirl/MainZIOVertxScala3.scala.txt
- build.sbt
- ui/src/api/starter.ts
- ui/src/components/ConfigurationForm/ConfigurationForm.consts.ts
- ui/src/components/ConfigurationForm/ConfigurationForm.helpers.ts
- ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.helpers.test.ts
Vert.X option as server implementation is available for all given Effect types
> 168 add vertx server option

- backend/src/main/scala/com/softwaremill/adopttapir/http/HttpApi.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/BuildView.scala
- backend/src/main/twirl/MainIOHttp4s.scala.txt
- backend/src/main/twirl/MainIOHttp4sScala3.scala.txt
- backend/src/main/twirl/MainZIOHttp4s.scala.txt
- backend/src/main/twirl/MainZIOHttp4sScala3.scala.txt
- backend/src/test/scala/com/softwaremill/adopttapir/test/ServiceFactory.scala
- build.sbt
> replaced blaze with ember

- backend/src/main/scala/com/softwaremill/adopttapir/template/BuildView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectGenerator.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala
Set proper logger dependencies for every implementation and add logback.xml for proper implementations
> Set proper logger dependencies 

- backend/src/main/twirl/MainZIOHttp4s.scala.txt
- backend/src/main/twirl/MainZIOHttp4sScala3.scala.txt
[Issue: 374](https://github.com/softwaremill/adopt-tapir/issues/374)
> Deprecation warning in Adopt Tapir starter project (ZIO + http4s)

- backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala
When it is configured to do so. The IO(delete) operation was wrapped into another IO (blocking in this case) operation therefore only the outer was performed during the execution time. The problem was also indicated during compilation:
```
[warn] -- [E175] Potential Issue Warning: /Users/jcentkowski/workspace/sml/adopt-tapir/backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala:39:8
[warn] 39 |        for
[warn]    |        ^
[warn]    |        discarded non-Unit value of type cats.effect.IO[Unit]
[warn] 40 |          dir <- destinationDir
[warn] 41 |          _ <- dir.delete().pure[IO]
[warn] 42 |        yield ()
[warn] -- [E175] Potential Issue Warning: /Users/jcentkowski/workspace/sml/adopt-tapir/backend/src/main/scala/com/softwaremill/adopttapir/starter/fi …
```
> fix: ensure that FilesManager.deleteFilesAsStatedInConfig deletes

- .github/workflows/adopt-tapir-ci.yml
- backend/src/main/scala/com/softwaremill/adopttapir/metrics/Metrics.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterModel.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequest.scala
- backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequestValidator.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/BuildView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectGenerator.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/EndpointsSpecView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/EndpointsView.scala
- backend/src/main/scala/com/softwaremill/adopttapir/template/scala/MainView.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/FileOperation.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/FormValidatorTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala
- backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterRequestGenerators.scala
- backend/src/test/scala/com/softwaremill/adopttapir/test/ShowHelpers.scala
- development/http-client.http
- ui/src/api/starter.ts
- ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx
- ui/src/components/ConfigurationForm/ConfigurationForm.consts.ts
- ui/src/components/ConfigurationForm/ConfigurationForm.helpers.ts
- ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.component.test.tsx
- ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.consts.test.ts
- ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.helpers.test.ts
- ui/src/hooks/useInitialData.ts
This PR renames "Effect type" and available options:
> Rename "effect type" to "stack type"

- .scala-steward.conf
- build.sbt
- ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx
- ui/src/components/ConfigurationForm/ConfigurationForm.consts.ts
- ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.component.test.tsx
- ui/src/hooks/useInitialData.ts
Also auto-select implementation when stack is changed
Also updates scala 3 version to 3.4.2
> Update defaults to Ox+Netty+ScalaCLI
