softwaremill/adopt-tapir

.github/workflows/adopt-tapir-ci.yml, backend/src/main/resources/webapp/index.html, build.sbt
Adds a (very) basic `index.html` and a GitHub Action to publish an image to Docker Hub on every push to `main`.
The GCP deployment is set up in https://github.com/softwaremill/gcp-sml-internal-iac/tree/main/apps/base/adopt-tapir. Flux automatically picks the newest image from Docker Hub when it's published and deploys it to GCP.
The deployed webapp (from the `deployment` branch until the PR is merged) is available at https://adopt-tapir.softwaremill.com.
Closes #20.
=> Deployment

ui/public/index.html, ui/src/App.styles.ts, ui/src/App.tsx, ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx, ui/src/components/ConfigurationForm/ConfigurationForm.styles.ts, ui/src/components/Sidebar/Sidebar.component.tsx, ui/src/components/Sidebar/Sidebar.styles.ts, ui/src/theme.ts
Improved fronted app styling responsiveness to satisfy screens as low as 300px wide. Configuration form now accepts `isEmbedded` prop that will modify the behavior of form header and styling breakpoints. Improved a base theme to adjust font sizes based on the screen resolution.
=> imp(): make frontend app styling responsive

backend/src/main/scala/com/softwaremill/adopttapir/Dependencies.scala, backend/src/main/scala/com/softwaremill/adopttapir/Main.scala, backend/src/main/scala/com/softwaremill/adopttapir/metrics/Metrics.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterService.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterApi.scala, development/http-client.env.json, development/http-client.http
Example of an output: 
```
adopt_tapir_starter_generated_total{projectName="projectname",groupId="com.softwaremill",serverEffect="FutureEffect",serverImplementation="Akka",tapirVersion="1.0.0",addDocumentation="true",jsonImplementation="Jsoniter",} 1.0
```
closes #36
=> Starter metrics

backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterService.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectTemplate.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/scala/EndpointsSpecView.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/FileOperation.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceInTests.scala, backend/src/test/scala/com/softwaremill/adopttapir/template/ProjectTemplateInTests.scala, backend/src/test/scala/com/softwaremill/adopttapir/template/scala/FrameworkEndpointsSpecView.scala, backend/src/test/twirl/FrameworkEndpointsSpec.scala.txt, backend/src/test/twirl/FrameworkEndpointsSpecZIO.scala.txt
When `addMetrics` is selected and `StarterServiceITTest` is called
generate `FrameworkEndpointsSpec.scala` that verifies if metrics
endpoint is available and returns expected result.
Note that the spec in question is only compiled for tests and doesn't
polute the generated production code.
For development purposes one can examine the spec by calling:
```
com.softwaremill.adopttapir.starter.FileOperation
```
end examining their output.
Closes #6
=> chore: add metrics endpoint verification to framework endpoints spec

backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectTemplate.scala, backend/src/main/twirl/EndpointsSpec.scala.txt, backend/src/main/twirl/EndpointsSpecZIO.scala.txt
Changes:
* instatiate 'unwrapper' only when server effect is not ZIOEffect
* call 'toString' from one place (in `GenerateFile` constructor)
* add empty line package definition and import so that readability is
improved in `EndpointsSpec[ZIO].scala.txt` templates
=> chore: micro-organize EndpointsSpec.scala generation

backend/src/main/twirl/MainFutureAkka.scala.txt, backend/src/main/twirl/MainFutureNetty.scala.txt, backend/src/main/twirl/MainIOHttp4s.scala.txt, backend/src/main/twirl/MainIONetty.scala.txt, backend/src/main/twirl/MainZIOHttp4s.scala.txt, backend/src/main/twirl/MainZIOhttpZIO.scala.txt
When running server is started there is the following information
written:
```
(...) Press any key to exit.
```
however pressing any key doesn't exit the server unless `ENTER` is
pressed. In fact pressing just `ENTER` works hence information was
modified to:
```
(...) Press ENTER key to exit.
```
=> fix: information on how to terminate the running server

backend/src/main/twirl/MainFutureAkka.scala.txt, backend/src/main/twirl/MainFutureNetty.scala.txt, backend/src/main/twirl/MainIOHttp4s.scala.txt, backend/src/main/twirl/MainIONetty.scala.txt, backend/src/main/twirl/MainZIOHttp4s.scala.txt, backend/src/main/twirl/MainZIOhttpZIO.scala.txt, backend/src/test/scala/com/softwaremill/adopttapir/template/ProjectTemplateInTests.scala, backend/src/test/scala/com/softwaremill/adopttapir/template/scala/FrameworkEndpointsSpecView.scala, backend/src/test/twirl/FrameworkEndpointsSpec.scala.txt, backend/src/test/twirl/FrameworkEndpointsSpecZIO.scala.txt
When `addDocumentation` is selected and `StarterServiceITTest` is called
generate `FrameworkEndpointsSpec.scala` that verifies if docs
endpoint is available and returns expected result.
Note that the spec in question is only compiled for tests and doesn't
polute the generated production code.
For development purposes one can examine the spec by calling:
```
com.softwaremill.adopttapir.starter.FileOperation
```
end examining their output.
=> chore: add docs endpoint verification to framework endpoints spec

.github/workflows/adopt-tapir-ci.yml, README.md, backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequest.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala
At present running IT tests in CI takes ~28m. Add possibility to
scale configurations to multiple nodes over JSON implementation and
Scala version values.
By default nothing changes and all configurations are executed however
one can restrict them by providing comma separated values to JSON env
variable e.g:
```
JSON="Circe,No" sbt 'ItTest / test'
```
results in running integration tests only for configurations that JSON
is either disabled (`No`) or using `Circe` implementation.
It is used in CI to spawn 4 jobs in parallel.
Additionally one can restrict it with Scala version e.g. combined with JSON
```
JSON=No SCALA=Scala2 sbt 'ItTest / test'
```
results in integration tests for `Scala 2` with JSON disabled being integration
tested.
Closes #97.
=> chore: add possibility to restrict/run in parallel IT tests

backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala
The `file.delete` for directory sometimes fails on recursive directories
removal. Set it to ignore IO exceptions as temp directory is going to be
removed anyway by system.
Part of #99.
=> fix: ignore IO exceptions during IT resources cleanup 

backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterConfig.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectTemplate.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/FileOperation.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala
Scala version is part of the request and as such is no longer needed to be
preconfigured. Remove it from the StarterConfig and remove StarterConfig
from ProjectTemplate parameters as it is no longer used there.
=> chore: remove scala version from starter config

.github/workflows/adopt-tapir-ci.yml
Currently version `18.04` is used and it is being flagged in CI that
this version is deprecated with the following warning:
```
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
```
Closes #117
=> chore: upgrade GitHub CI base image to 22.04

.github/workflows/adopt-tapir-ci.yml, .github/workflows/scala-steward.yml, build.sbt
The following components were updated for both CI workflow and Scala
Steward (unless mentioned):
* ubuntu to 22.04 (Scala Steward)
* JDK to version 17 (the latest LTS)
* actions/checkout to v3
* actions/setup-java to v3
* actions/cache to v3
* note that docker base image was also upgraded to JDK 17
('eclipse-temurin:17.0.4_8-jdk-jammy' to be precise)
=> chore: upgrade CI components

backend/src/main/scala/com/softwaremill/adopttapir/metrics/Metrics.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterModel.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequest.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/FileOperation.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/api/FormValidatorTest.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterRequestGenerators.scala, ui/src/api/starter.ts, ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx, ui/src/components/ConfigurationForm/ConfigurationForm.consts.ts, ui/src/components/ConfigurationForm/ConfigurationForm.styles.ts, ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.component.test.tsx, ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.consts.test.ts
New radio button group was added to the UI ('Builder') that contains the
following values (according to their web page names):
* sbt (default)
* Scala CLI
Here is the upgraded `adopt-tapir` configuration form with the default values:
Notes:
* UI tests were extended to validate new configuration values
* default builder value (Sbt) was removed from StarterRequest and
StarterDetails as it is supported in UI now
* new fronted was successfully, manually tested against
https://adopt-tapir.softwaremill.com/ as backend is already deployed
Closes #45
=> feat: add builder selection to adopt-tapir UI

backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectGenerator.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/scala/EndpointsView.scala, backend/src/main/twirl/Endpoints.scala.txt
* In generated project list of API endpoints is created once
* Updated endpoints order in case classes and template
* In `EndpointsView.scala` updated code order, so that it corresponds to the aforementioned changes
=> Creating list of endpoints once

.mergify.yml
Updated `.mergify.yml` - specified all names of GitHub Action Check Jobs that need to pass for automatic merge to happen, thus fixing the "automatic merge does not work" problem.
=> Fixed mergify configuration for automatic merge of PRs that passess validation.

backend/src/main/resources/template/README_scala-cli.md
Apart from the obvious typos there refer to the product as `Scala CLI`
(the same way product is referred in its homepage).
=> fix: typos in the Scala CLI README.md template

ui/src/components/ApiCallAddons/ApiCallAddons.component.tsx, ui/src/components/CommonSnackbar/CommonSnackbar.component.tsx, ui/src/components/CommonSnackbar/index.ts, ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx
There are two places where snackbar is used therefore it makes sense to introduce CommonSnackbar so that their look & feel is aligned. Considering these two usage the CommonSnackbar has properties according to this interface:
```
type Props = {
onClose: () => void;
open: boolean;
duration?: number;
message?: String;
severity?: AlertColor;
};
```
Note that `ApiCallAddons` implementation contained `outlined` property additionally but it was gave up due to being less readable on smaller screens (overlapped with background).
Result of #75
=> feat: introduce CommonSnackbar

ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx
So that `useEffect` functionality is better described. Result of #75
=> chore: move shared configuration application to a method

ui/src/api/starter.ts, ui/src/components/FileTreeView/FileTreeView.component.tsx, ui/src/components/FileTreeView/FileTreeView.types.ts, ui/src/pages/PreviewStarterPage/PreviewStarterPage.component.tsx, ui/src/pages/RootPage/RootPage.styles.ts
The following improvements were added:
* _preview_ layout was improved to offer more space for the editor (files tree was narrowed, code editor was expanded, margins got thinner)
* all `src` folders are opened
* `Main.scala` file content is selected in the editor
* folder representation was modified to slightly visually distinguish between folder closed/opened states
Here is the look & feel of `preview`:
Closes #170
=> feat: preview files ux improvements

backend/src/main/scala/com/softwaremill/adopttapir/metrics/Metrics.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterService.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/content/ContentService.scala
At present preview is not reported as a metric. Add _operation_ label to the existing _adopt_tapir_starter_generated_total_ metric. It can contain the following values `preview` and `generate`. As a result both `preview` and `generate` operations can be independently tracked.
Part of #175
=> feat: add label to distinguish generate ZIP/preview operations in metric

.github/workflows/adopt-tapir-ci.yml
It is a bit confusing if one of integration tests is failing due to either unit tests or docker image build failure.
Closes #197
=> chore: move unit tests (with lint) and image build to dedicated job

ui/src/api/starter.ts, ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx, ui/src/hooks/useSharedConfig.ts
Note that clicking the `preview` button in the embedded form mode results in:
* generation of URL that contains the current configuration as query params with an extra `preview=true` parameter added
* opening of the URL in question in the new window
* configuration application followed by the switch to `preview` mode
Closes #169
=> feat: enable 'preview' button in the embedded form

.mergify.yml
When new jobs/steps were introduced the existing ones were renamed. As a result `mergify` was no longer able to evalute the rules. Update rules to reflect new job names.
Follow-up to #197
=> fix: update `.mergify.yml` rules to reflect the recent CI changes

backend/src/main/resources/template/README_scala-cli.md, backend/src/main/scala/com/softwaremill/adopttapir/template/BuildView.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectGenerator.scala, backend/src/main/twirl/scalaCliBuild.scala.txt, backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala
The following suggestions were implemented:
* entry about importing Scala CLI project to popular IDEs (Metals / IntelliJ) was added to the generated `README.md`
* project files (`*.sc`) were renamed to `*.scala` so that IDEs are not confused, what is more `test.sc` was renamed to `build.test.scala` to better reflect its intent
* comment-based `using` notation is used in the generated project files as it is the recommended way of doing it
Note that `.gitignore` was not introduced as it is a good candidate for both `Build tools` and as such will be added as a part of separate PR.
Part of #194
=> feat: tune the generated Scala CLI project according to the guidelines

backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectGenerator.scala, backend/src/main/twirl/gitignore.scala.txt, backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala
Generate '.gitignore' file for both build tools (sbt and Scala CLI) that ignores IntelliJ and Metals IDEs project/support files.
Note that both build tools projects were tested under both IntelliJ and Metals to confirm if correct files are excluded from `Git` by:
* importing projects to both IntelliJ and Metals IDEs
* committing files according to the `.gitignore`
* checking if only source, build tool specific files were committed
* cloning and importing projects again
The `.gitignore` file content per build tool:
* _sbt_:
```
.idea/
.metals/
.vscode/
.bloop
target
metals.sbt
project/project
```
* _Scala CLI_:
```
.idea/
.metals/
.vscode/
.bsp/
.scala-build/
```
Closes #194
=> feat: generate '.gitignore' file for IntelliJ / Metals IDEs

ui/src/theme.ts
Issue: when embedded form is viewed under Safari it divides button into 2 lines.
Solution: reduce the default padding from `16px` to `14px` so that they fit into one line.
Follow-up to #169
=> fix: reduce buttons padding to 14px

ui/src/components/FileContentView/FileContentView.component.tsx, ui/src/components/FileContentView/FileContentView.styles.ts, ui/src/components/FileTreeView/FileTreeView.styles.ts, ui/src/pages/PreviewStarterPage/PreviewStarterPage.component.tsx, ui/src/pages/PreviewStarterPage/PreviewStarterPage.styles.ts, ui/src/pages/RootPage/RootPage.styles.ts
According to [SO](https://stackoverflow.com/a/61844861) it was determined that the top container has to have
fixed height (could be `100vh` related but cannot be `100%` related) and
then inner container can have 100% height. Note that `minHeight` was set to `450px`.
Apart from the the following changes were applied
* all margins were reduced so that file/code areas use more screen
estate
* selected file (in file view) is no longer bolded (but still
highlighted so that there is no doubt that it is selected) so that it
doesn't take more space
* proportion between file and content views was modified so that more
space is available for file view (potentially reducing the need for
horizontal scrollbar)
Here is the current look & feel for `1794px` width:
Closes #92
=> fix: don't show double vertical scrollbars on sbtx file

ui/src/components/FileContentView/FileContentView.component.tsx
In **SyntaxHighlighter** component:
if we set `showInlineLineNumbers` property to `false`, numbers will be shown in a separate element.
When styled accordingly, it will be no different than what we have now:
Checked on Safari, Chrome, Firefox and Opera.
Fixes #193
=> fix: prevent copying line numbers in Safari

ui/src/components/FileTreeView/FileTreeView.styles.ts
Before:
After:
Part of/fix for #219
=> fix: highlight of opened file in preview's tree view

.github/workflows/adopt-tapir-ci.yml
Despite [docs](https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/) it seems that `ubuntu-latest` is still `20.04` hence run all actions on the specific, `22.04` version.
=> chore: unify CI/CD images to run on the same ubuntu version

backend/src/main/twirl/MainFutureNetty.scala.txt, backend/src/main/twirl/MainFutureNettyScala3.scala.txt, backend/src/main/twirl/MainFutureVertx.scala.txt, backend/src/main/twirl/MainFutureVertxScala3.scala.txt, backend/src/main/twirl/MainIOHttp4s.scala.txt, backend/src/main/twirl/MainIOHttp4sScala3.scala.txt, backend/src/main/twirl/MainIONetty.scala.txt, backend/src/main/twirl/MainIONettyScala3.scala.txt, backend/src/main/twirl/MainIOVertx.scala.txt, backend/src/main/twirl/MainIOVertxScala3.scala.txt, backend/src/main/twirl/MainZIOHttp4s.scala.txt, backend/src/main/twirl/MainZIOHttp4sScala3.scala.txt, backend/src/main/twirl/MainZIOVertx.scala.txt, backend/src/main/twirl/MainZIOVertxScala3.scala.txt
Refactor templates:
-  Use built-in methods for reading from and printing to the console in ZIO and cats. 
- Change the name of the env variable for setting the port number to HTTP_PORT.
=> Refactor templates for cats and zio

backend/src/main/scala/com/softwaremill/adopttapir/Dependencies.scala, backend/src/main/scala/com/softwaremill/adopttapir/Main.scala, backend/src/main/scala/com/softwaremill/adopttapir/config/Config.scala, backend/src/main/scala/com/softwaremill/adopttapir/http/Http.scala, backend/src/main/scala/com/softwaremill/adopttapir/http/HttpApi.scala, backend/src/main/scala/com/softwaremill/adopttapir/infrastructure/CorrelationId.scala, backend/src/main/scala/com/softwaremill/adopttapir/logging/FLogging.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterService.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/formatting/GeneratedFilesFormatter.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/FileOperation.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/content/ContentServiceTest.scala, backend/src/test/scala/com/softwaremill/adopttapir/test/TestDependencies.scala
`CorrelationId` no longer is created using `unsafeRunSync`. It is now initialized in `Main` and passed down as an implicit parameter.
=> Refactor CorrelationId

backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterService.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/files/FilesManager.scala, backend/src/main/scala/com/softwaremill/adopttapir/util/ZipArchiver.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala, backend/src/test/scala/com/softwaremill/adopttapir/util/ZipArchiverTest.scala
Conventionally there's a parent directory in a zip, so that `unzip file.zip` won't mess up the directory where it's called. In this case, the project name will be used as the directory name.
=> Put zipped files in a root directory

backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterModel.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequest.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequestValidator.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/BuildView.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/scala/MainView.scala, backend/src/main/twirl/MainFuturePekko.scala.txt, backend/src/main/twirl/MainFuturePekkoScala3.scala.txt, backend/src/test/scala/com/softwaremill/adopttapir/starter/api/FormValidatorTest.scala, ui/src/api/starter.ts, ui/src/components/ConfigurationForm/ConfigurationForm.consts.ts, ui/src/components/ConfigurationForm/ConfigurationForm.helpers.ts, ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.consts.test.ts, ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.helpers.test.ts
The following change add Apache Pekko to server implementations for the `Future` effect for both `Scala 2` and `Scala 3` destinations.
Here is the UI screenshot:
Note that integration is being confirmed through the integration, UI and manual tests.
Closes #446 .
=> feat: add Apache Pekko to server implementations

.github/workflows/adopt-tapir-ci.yml
So that the newest actions could be used (see the corresponding issue for details).
The following actions were upgraded:
* actions/checkout@v4
* coursier/cache-action@v6
* VirtusLab/scala-cli-setup@v1
* docker/login-action@v3
Closes #480
=> chore: upgrade GH Actions to the latest available major versions

backend/src/main/scala/com/softwaremill/adopttapir/Dependencies.scala, backend/src/main/scala/com/softwaremill/adopttapir/http/Http.scala, backend/src/main/scala/com/softwaremill/adopttapir/http/HttpApi.scala, backend/src/main/scala/com/softwaremill/adopttapir/infrastructure/Json.scala, backend/src/main/scala/com/softwaremill/adopttapir/metrics/VersionApi.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterService.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterApi.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/content/ContentModel.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/formatting/GeneratedFilesFormatter.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectGenerator.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/FileOperation.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala, backend/src/test/scala/com/softwaremill/adopttapir/starter/api/StarterApiTest.scala, backend/src/test/scala/com/softwaremill/adopttapir/test/Requests.scala
The following warnings are fixed:
* about unused imports and parameters
* about discarded non-Unit value of type
* about `apirStaticContentEndpoints is deprecated`
_Note_
Warnings about `unused import` from Twirl generated sources e.g.
```
[warn] /Users/jcentkowski/workspace/sml/adopt-tapir/backend/src/main/twirl/Endpoints.scala.txt:1:1: unused import
[warn] @(
[warn] ^
```
were not fixed.
The problem is that regardless of what is written in [scala.lang.org](https://www.scala-lang.org/2021/01/12/configuring-and-suppressing-warnings.html) neither `src` nor `origin` nor `site` filters are available as of `scalac` version `3.3.1` - here is the output of `help` command
```
$ scalac -Wconf:help
Configure compiler warnings.
Syntax: -Wconf:<filters>:<action>,<filters>:<action>,...
multiple …
```
=> Fix compilation warnings

.github/workflows/adopt-tapir-ci.yml, backend/src/main/scala/com/softwaremill/adopttapir/starter/StarterModel.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequest.scala, backend/src/main/scala/com/softwaremill/adopttapir/starter/api/StarterRequestValidator.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/BuildView.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/ProjectGenerator.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/scala/EndpointsSpecView.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/scala/EndpointsView.scala, backend/src/main/scala/com/softwaremill/adopttapir/template/scala/MainView.scala, backend/src/main/twirl/EndpointsSpecSync.scala.txt, backend/src/main/twirl/MainSyncNettyScala3.scala.txt, backend/src/test/scala/com/softwaremill/adopttapir/starter/StarterServiceITTest.scala, backend/src/test/scala/com/softwaremill/adopttapir/test/ServiceFactory.scala, build.sbt, ui/src/api/starter.ts, ui/src/components/ConfigurationForm/ConfigurationForm.component.tsx, ui/src/components/ConfigurationForm/ConfigurationForm.consts.ts, ui/src/components/ConfigurationForm/ConfigurationForm.helpers.ts, ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.consts.test.ts, ui/src/components/ConfigurationForm/__tests__/ConfigurationForm.helpers.test.ts
This PR adds the `tapir-netty-sync` backend. It appears as a separate `Sync` effect type, available only for `Netty` and `Scala 3`. This backend has no "effect" per se, it's the direct-style monadless one, based on Netty and Loom. In order to test this properly, I added a new CI matrix axis for the effect. As a result, quite a lot of parallel builds are generated, but the overall build time doesn't increase (it's actually faster: ~13m instead of ~25m).
Additionally, I bumbed JDK to 21 in the workflow, leaving Java 17 for integration tests with effect != "Sync".
=> Support netty-sync
